mutation sendMessage($conversationId: Int!, $text: String!, $timestamp: DateTime!) {
  sendMessage(conversationId: $conversationId, text: $text, timestamp: $timestamp) {
    id
    authorType
    authorId
    content
    createdAt
  }
}
