source "https://rubygems.org"

gem "fastlane"
gem "byebug"
gem "cocoapods"
gem "json"
gem "colorize"
gem "rexml"
gem "activesupport"

plugins_path = File.join(File.dirname(__FILE__), 'Pluginfile')
eval_gemfile(plugins_path) if File.exist?(plugins_path)
